CREATE TABLE IF NOT EXISTS `users` (
  `username` CHAR (255) PRIMARY KEY NOT NULL,
  `password` VARCHAR (255) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `servers` (
  `token` CHAR (100) PRIMARY KEY UNIQUE NOT NULL,
  `wid` VARCHAR (255) UNIQUE NOT NULL,
  `verified` BOOLEAN NOT NULL DEFAULT FALSE,
  `devel` BOOLEAN NOT NULL DEFAULT FALSE,
  `handlegroups` BOOLEAN NOT NULL DEFAULT TRUE,
  `handlebroadcast` BOOLEAN NOT NULL DEFAULT FALSE,
  `user` CHAR (36) DEFAULT NULL REFERENCES `users`(`username`),
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `webhooks` (
  `context` CHAR (255) NOT NULL REFERENCES `servers`(`token`),
  `url` VARCHAR (255) NOT NULL,
  `forwardinternal` BOOLEAN NOT NULL DEFAULT FALSE,
  `trackid` VARCHAR (100) NOT NULL DEFAULT '',
  `extra` BLOB DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `webhooks_pkey` PRIMARY KEY (`context`, `url`)
);

INSERT INTO migrations (id) VALUES 
('1'),
('202207131700'),
('202209281840'),
('202303011900')
;